personal_site/urls.py
from django.urls import path, include
from . import views
from .views import home, others, time

app_name = "story_4"

urlpatterns = [
    path("",views.home,name="home"),
    path("others/",views.others,name="others"),
    path("time/<str:jump>/",views.time,name="time")
]

story_1/urls.py
from django.urls import path, include
from . import views
from .views import story_1

app_name = "story_1"

urlpatterns = [
    path("",views.story_1,name="home")
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import blank_link

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story_4/",include("personal_site.urls")),
    path("story_1/",include("story_1.urls")),
    path("",views.blank_link,name="blank")
]

personal_site/models.py
from django.db import models

# Create your models here.

story_1/models.py
from django.db import models

# Create your models here.

personal_site/views.py
from django.shortcuts import render, HttpResponse
import datetime

def home(request):
    context = {
        "type" : "home"
    }
    return render(request,"personal_site/index.html",context)

def others(request):
    context = {
        "type" : "others"
    }
    return render(request,"personal_site/others.html",context)

def time(request,jump):
    am_or_pm = (datetime.datetime.now() + datetime.timedelta(hours = int(jump))).strftime("%p")
    context = {
        "time" : datetime.datetime.now() + datetime.timedelta(hours = int(jump)),
        "am_or_pm" : "午前" if am_or_pm == "AM" else "午後"
    }
    return render(request,"personal_site/time.html",context)

story_1/views.py
from django.shortcuts import render

def story_1(request):
    context = {
        "type" : "story_1"
    }
    return render(request,"story_1/index.html",context)

story_4/views.py
from django.shortcuts import render

def blank_link(request):
    return render(request,"personal_site/navigation.html")

personal_site/templates/personal_site/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome-->
    <script src="https://kit.fontawesome.com/21004379e8.js" crossorigin="anonymous"></script>
    
    <!-- External CSS -->
    <link rel="stylesheet" href={% static 'css/styles.css' %}>

    <!-- Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho&display=swap" rel="stylesheet">
    <title>Steven's Website</title>
  </head>
  <body>
    {% include 'personal_site/navbar.html' %}
    {% block content %}
    {% endblock %}
    <footer class="page-footer footer font-small blue bg-main text-light">
        <div class="footer-copyright text-center py-3">© 2020 Made by:
            Steven Sim
        </div>
    </footer>
  <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src={% static "js/scripts.js" %}></script>

    </body>
</html>

personal_site/templates/personal_site/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-main sticky-top">
    <div class="container">
        <i class="fas fa-laptop-code text-light"></i>
        <a class="navbar-brand" href="#">Steven's Website</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">

            {% if type == "home" %}
                <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="#about">About</a>
                <a class="nav-item nav-link" href="#contact">Contact</a>
                <a class="nav-item nav-link" href={% url 'story_4:others' %}>Others</a>
                <a class="nav-item nav-link" href={% url 'story_1:home' %}>Story 1</a>
            {% elif type == "others" %}
                <a class="nav-item nav-link " href={% url 'story_4:home' %}>Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href={% url 'story_4:home' %}>About</a>
                <a class="nav-item nav-link" href={% url 'story_4:home' %}>Contact</a>
                <a class="nav-item nav-link active" href="#">Others</a>
                <a class="nav-item nav-link" href={% url 'story_1:home' %}>Story 1</a>
            {% elif type == "story_1" %}
                <a class="nav-item nav-link " href={% url 'story_4:home' %}>Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href={% url 'story_4:home' %}>About</a>
                <a class="nav-item nav-link" href={% url 'story_4:home' %}>Contact</a>
                <a class="nav-item nav-link" href={% url 'story_4:others' %}>Others</a>
                <a class="nav-item nav-link active" href="#">Story 1</a>
            {% endif %}
        </div>
        </div>
    </div>
    
</nav>

personal_site/templates/personal_site/navigation.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Navigation Site</title>
    <style>
        .bg-navigation{
            background-image: linear-gradient(45deg,gold,yellow);
        }
    </style>
  </head>
  <body class="bg-navigation">
    <div class="container vh-100 vw-100 d-flex justify-content-center align-items-center flex-column">
        <div class="w-lg-50 h-75 w-sm-75 bg-light rounded-lg p-3 text-center">
            <h1 class="mt-2">Welcome!</h1>
            <p class="mb-0">Hello! I'm Steven.</p>
            <p>Here you can find my Web Design and Programming Projects :)</p>

            <div class="text-left ml-lg-5">
                <ul>
                    <li><a href={% url 'story_1:home' %}>Story 1 : Intro to Web Development</a></li>
                    <li><a href={% url 'story_4:home' %}>Story 4 : Django Views and Templates</a></li>
                    <li><a href="http://ppw-stories-steven.herokuapp.com/story_5/">Story 5 : Django Models</a></li>
                    <li><a href="http://ppw-stories-steven.herokuapp.com/story_6/">Story 6 : Test Driven Development</a></li>
                    <li><a href="http://tk1-ppw.herokuapp.com/">Group Project 1 : Online Shop</a></li>
                </ul>
            </div>
        </div>
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

personal_site/templates/personal_site/others.html
{% extends "personal_site/base.html" %}
{% block content %}
{% load static %}
      <div class="jumbotron h-with-nav m-0 d-flex flex-column justify-content-center align-items-center text-center">
        <h1 class="display-4">So you decided to come here</h1>
        <hr class="my-3 border-2">
        <p>This page is dedicated to things I like</p>
        <p class="lead">
          <a class="btn btn-main btn-lg" href={% url 'story_4:home' %} role="button">Go back</a>
        </p>
      </div>

    <div class="bg-main2 pb-2">
      <div class="container text-center">
        <h1 class="py-3 m-0">What I like</h1>
        <div class="row text-center">
          <div class="col-lg-6 col-sm-12 p-3 h-with-nav-half d-flex justify-content-center align-items-center">
            <img class="anime-art" src={% static "images/nichijou.jpg" %}>
          </div>
          <div class="bg-main3 col-lg-6 col-sm-12 p-3 h-with-nav-half d-flex flex-column justify-content-center align-items-center rounded-lg">
            <h3 class="mb-4">Nichijou (日常)</h3>
            <p>Basically the sole thing that brought me into learning the Japanese Language</p>
            <p>It's very entertaining and I recommend anyone to watch it even if you're not into anime.</p>
            <a class="btn btn-main btn-md" href="https://myanimelist.net/anime/10165/Nichijou" role="button">See more about this</a>
          </div>
          <div class="col-lg-6 col-sm-12 p-3 h-with-nav-half mt-lg-2 d-flex justify-content-center align-items-center">
            <img class="anime-art" src={% static "images/tenki-cover.jpg" %}>
          </div>
          <div class="bg-main3 col-lg-6 mb-lg-2 mt-lg-2 col-sm-12 p-3 h-with-nav-half d-flex flex-column justify-content-center align-items-center rounded-lg">
            <h3 class="mb-4">Weathering With You (天気の子)</h3>
            <p>Even though I rarely watch movies especially anime movies, this one really kicks in, the graphics were just too good to be true.</p>
            <p>I watched this with my new college friends right before the first term started.</p>
            <a class="btn btn-main btn-md" href="https://myanimelist.net/anime/38826/Tenki_no_Ko?q=tenki%20no%20ko" role="button">See more about this</a>
          </div>
          <div class="col-lg-6 col-sm-12 p-3 h-with-nav-half mt-lg-2 d-flex justify-content-center align-items-center">
            <img class="anime-art" src={% static "images/kon.jpg" %}>
          </div>
          <div class="bg-main3 col-lg-6 mt-lg-2 col-sm-12 p-3 h-with-nav-half d-flex flex-column justify-content-center align-items-center rounded-lg">
            <h3 class="mb-4">K-ON! (けいおん)</h3>
            <p>I haven't yet finished this show but I already like it better than a lot that I have watched</p>
            <p>Not just the show, but I also really like the songs that they created</p>
            <a class="btn btn-main btn-md" href="https://myanimelist.net/anime/5680/K-On?q=k-on" role="button">See more about this</a>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center bg-main text-light">
      <h1 class="p-3 m-0">Vacation Pictures 2019</h1>
    </div>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block carousel-main" src={% static "images/1.jpg" %} alt="First slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Osaka Castle</h5>
            <p>大阪</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block carousel-main" src={% static "images/2.jpg" %} alt="Second slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Ginkaku-ji</h5>
            <p>銀閣寺、京都</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block carousel-main" src={% static "images/3.jpg" %} alt="Third slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Akihabara at Night</h5>
            <p>秋葉原、東京</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="d-block carousel-main" src={% static "images/4.jpg" %} alt="Fourth slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Shinjuku at Night</h5>
            <p>新宿、東京</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <!-- Modal Carousel Challenge -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header bg-main border-0">
            <h5 class="modal-title text-light" id="exampleModalLabel">More Pictures</h5>
            <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body bg-main2">
            <div id="carouselModal" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                <li data-target="#carouselModal" data-slide-to="0" class="active"></li>
                <li data-target="#carouselModal" data-slide-to="1"></li>
                <li data-target="#carouselModal" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block modal-pic" src={% static "images/architecture.jpg" %} alt="First slide">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>City</h5>
                    <p>from Pexels</p>
                  </div>
                </div>
                <div class="carousel-item">
                  <img class="d-block modal-pic" src={% static "images/aurora1.jpg" %} alt="Second slide">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>Aurora Borealis</h5>
                    <p>from Pexels</p>
                  </div>
                </div>
                <div class="carousel-item">
                  <img class="d-block modal-pic" src={% static "images/aurora2.jpg" %} alt="Third slide">
                  <div class="carousel-caption d-none d-md-block">
                    <h5>Aurora Borealis</h5>
                    <p>from Pexels</p>
                  </div>
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselModal" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselModal" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          <div class="modal-footer bg-main  border-0">
            <h4 class="mr-auto text-light">楽しんでね</h4>
            <button type="button" class="btn btn-main4" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Carousel Button -->
    <div class="p-3 d-flex justify-content-center bg-main2">
      <button type="button" class="btn btn-main" data-toggle="modal" data-target="#exampleModal">
        See more pictures :)
      </button>
    </div>

    <div class="h-with-nav bg-main3 d-flex flex-column justify-content-center align-items-center">
      <div class="container text-center">
            <h1 class="pt-3 mb-5">A bit back story of how I made friends in Universitas Indonesia</h1>
            <p>After getting accepted into UI (Universitas Indonesia) through SNMPTN, I knew life was going to change alot at college since none of my high-school friends will be in the same faculty here so I had to make friends.</p>
            <p>3 days after the school report card verification, I got invited to the group chat with newly accepted students, there was only ~200 people and most of them still don't know each other so we just said "Hi" and "Welcome" to anyone who had just gotten into the group.</p>
            <p>But then, there's this one person who keeps talking about japanese stuff (anime, manga, etc.) with the group, and that's where I know I have someone with a common interest, so I joined the conversation.</p>
            <p>Although in just a few hours, some people complained that the chat was getting flooded with unimportant talk, so in the aftermath we created a group for people who like Japanese stuff especially anime, manga, or learning the language.</p>
            <p class="m-0 pb-3">And that group, is where I made alot of friends that I still can rely on today.</p>
      </div>
    </div>
    {% endblock content %}

personal_site/templates/personal_site/time.html
{% extends "personal_site/base.html" %}
{% block content %}
<div class="bg-main2">
    <div class="container h-onepage d-flex justify-content-center align-items-center flex-column text-light">
        <h1>It is now:</h1>
        <h1>{{ time }}</h1>

        <div class="d-flex justify-content-center align-items-center flex-column mt-3 time-japanese">
            <h1>現在は</h1>
            <h1>{{time|date:"Y"}}年{{time|date:"m"}}月{{time|date:"d"}}日</h1>
            <h1>{{am_or_pm}}{{time|date:"h"}}時{{time|date:"i"}}分</h1>
        </div>
    </div>
</div>
{% endblock content %}

story_1/templates/story_1/index.html
{% extends "personal_site/base.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static "story_1/css/styles.css" %}>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/21004379e8.js" crossorigin="anonymous"></script>
    

    <div class="flex">
        <div class="left-side">
            <section class="section1">
                <img class="pfp" src={% static "story_1/images/pfp.jpg" %}>
                <h1>Steven Sim</h1>
                <h5><u>Fullstack Web Developer</u></h5>
            </section>
            <section class="section2 flex-start">
                <div>
                    <h3>Contact me</h3>
                    <hr class="contact-hr">
                    <div class="contact-text flex-left">
                        <i class="far fa-envelope"></i>
                        <p>stevensim226@gmail.com</p>
                    </div>
                    <div class="contact-text flex-left">
                        <i class="fas fa-phone-square-alt"></i>
                        <p>0812 - XXXX - XXXX</p>
                    </div>
                    <div class="contact-text flex-left">
                        <i class="far fa-compass"></i>
                        <p>North Jakarta, Indonesia</p>
                    </div>
                    <div class="contact-text flex-left">
                        <i class="fab fa-line"></i>
                        <p>steven_sim420</p>
                    </div>
                </div>
                <div class="contact center column">
                    <a href="http://instagram.com/stevensim226">
                        <div class="contact-btn center">
                            <i class="fab fa-instagram"></i>
                        </div>
                    </a>
                    <a href="https://www.linkedin.com/in/steven-sim-a242a3194/">
                        <div class="contact-btn center">
                            <i class="fab fa-linkedin"></i>
                        </div>
                    </a>
                    <a href="http://stevensim226.netlify.com">
                        <div class="contact-btn center">
                            <i class="fas fa-globe-asia"></i>
                        </div>
                    </a>
                    <a href="https://gitlab.com/stevensim226">
                        <div class="contact-btn center">
                            <i class="fab fa-gitlab"></i>
                        </div>
                    </a>
                </div>
            </section>
        </div>

        <div class="right-side">
            <section class="section3 center">
                <h1>Welcome to Steven's Website!</h1>
            </section>
            <section class="section4 center">
                <div class="about-me">
                    <i class="far fa-user"></i>
                    <h1>About me</h1>
                    <hr>
                    <p class="breadcrumb">18 years old / Jakarta, Indonesia</p>
                    <p>
                        Hello there!
                        My name is Steven, I am a student majoring Computer Science at Universitas Indonesia,
                        currently focusing on Fullstack web development and also learning embedded systems!
                    </p>
                    <p>
                        I am also interested in learning languages! both human and computer languages,
                        I am a native speaker in Bahasa Indonesia, and is fluent in both English and also Japanese.
                    </p>
                    <p>
                        As for my hobby, I like programming especially in fullstack web development,
                        I have learned several frameworks related to it such as Django, React.js etc.
                        and is also familiar with Javascript
                    </p>
                </div>
                <div class="jakun center column">
                    <img class="jakun-img" src={% static "story_1/images/jakun.jpg" %}>
                    <p class="caption">Me wearing UI's alma mater jacket in front of the rektorat building</p>
                </div>
            </section>
            <section class="section5 center">
                <div class="center column">
                    <i class="fas fa-school"></i>
                    <p class="inline">Education History</p>
                    <table>
                        <tr>
                            <th>School</th>
                            <th>Year</th>
                        </tr>
                        <tr>
                            <td>SD St. Yakobus</td>
                            <td>2006 - 2012</td>
                        </tr>
                        <tr>
                            <td>SMP St. Yakobus</td>
                            <td>2012 - 2016</td>
                        </tr>
                        <tr>
                            <td>SMA St. Yakobus</td>
                            <td>2016 - 2019</td>
                        </tr>
                        <tr>
                            <td>Universitas Indonesia</td>
                            <td>2019 -</td>
                        </tr>
                    </table>
                </div>
                <div class="center column">
                    <i class="fas fa-male"></i>
                    <p class="inline">Personal Information</p>
                    <table>
                        <tr>
                            <th colspan="2">Data</th>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>Steven Sim</td>
                        </tr>
                        <tr>
                            <td>NPM</td>
                            <td>1906293322</td>
                        </tr>
                        <tr>
                            <td>Class of</td>
                            <td>2019 (Maung)</td>
                        </tr>
                        <tr>
                            <td>Hobby</td>
                            <td>Programming</td>
                        </tr>
                    </table>
                </div>
                <div class="center column">
                    <i class="fas fa-laptop-code laptop-skills"></i>
                    <p class="inline">Skills</p>
                    <table>
                        <tr>
                            <th>Skill</th>
                            <th>Language</th>
                        </tr>
                        <tr>
                            <td>Programming</td>
                            <td>Python, Java, Javascript</td>
                        </tr>
                        <tr>
                            <td>Front-end</td>
                            <td>HTML, CSS, React.js</td>
                        </tr>
                        <tr>
                            <td>Back-end</td>
                            <td>Django</td>
                        </tr>
                        <tr>
                            <td>Embedded Systems</td>
                            <td>Raspberry Pi</td>
                        </tr>
                    </table>
                </div>
            </section>
        </div>
    </div>
    {% endblock content %}